### ISSUE TITLE
Null pointer reading reply from startWriteJob operation

### ISSUE THREAD

**Issue by dkocher** [SpectraLogic/ds3_java_sdk#138]
For a bulk start request with one file sized `0` bytes, the reesponse is 
```
<?xml version="1.0"?>
<MasterObjectList BucketName="test.cyberduck.ch" CachedSizeInBytes="0" ChunkClientProcessingOrderGuarantee="IN_ORDER" CompletedSizeInBytes="0" JobId="1ffbc34c-8a5a-4373-b8ff-70e58ca8dfb1" OriginalSizeInBytes="0" Priority="NORMAL" RequestType="PUT" StartDate="2015-12-22T15:17:21.000Z" Status="IN_PROGRESS" UserId="403020e4-02ac-4cf2-b84e-1d29a8980390" UserName="iterate" WriteOptimization="CAPACITY">
    <Nodes>
        <Node EndPoint="192.168.56.101" HttpPort="8080" Id="80b968b0-8df4-11e5-9255-0800279adf5d"/>
    </Nodes>
</MasterObjectList>
```

Reading the reply fails in `WriteJobImpl.<init>` with 
```
java.lang.NullPointerException
	at com.spectralogic.ds3client.helpers.WriteJobImpl.<init>(WriteJobImpl.java:46)
	at com.spectralogic.ds3client.helpers.Ds3ClientHelpersImpl.innerStartWriteJob(Ds3ClientHelpersImpl.java:70)
	at com.spectralogic.ds3client.helpers.Ds3ClientHelpersImpl.startWriteJob(Ds3ClientHelpersImpl.java:48)
```

**Comment by rpmoore** [comment]
What version of the SDK are you using?

**Comment by dkocher** [comment]
I just tested with v1.2.2.

**Comment by rpmoore** [comment]
Is this with BP v1.2?

**Comment by dkocher** [comment]
With `black_pearl_sim-1.2.0-1154042.vmdk`.

**Comment by rpmoore** [comment]
I think I know what is going on. I'll have a fix implemented later today.

**Comment by rpmoore** [comment]
The fix is now in the master branch.  A release that includes this fix will be available tomorrow.

**Comment by dkocher** [comment]
I can confirm that the null pointer has been fixed.
