### ISSUE TITLE
Unrecognized field "Latest"

### ISSUE THREAD

**Issue by dkocher** [SpectraLogic/ds3_java_sdk#152]
```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Latest" (class com.spectralogic.ds3client.models.bulk.BulkObject), not marked as ignorable (4 known properties: "Name", "InCache", "Length", "Offset"])
 at [Source: org.apache.http.conn.EofSensorInputStream@7979b8b7; line: 1, column: 683] (through reference chain: com.spectralogic.ds3client.models.bulk.MasterObjectList["Objects"]->java.util.ArrayList[0]->com.spectralogic.ds3client.models.bulk.Objects["Object"]->java.util.ArrayList[0]->com.spectralogic.ds3client.models.bulk.BulkObject["Latest"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:839)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1045)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1330)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:264)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:120)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:120)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2796)
	at com.spectralogic.ds3client.serializer.XmlOutput.fromXml(XmlOutput.java:116)
	at com.spectralogic.ds3client.commands.BulkResponse.processResponse(BulkResponse.java:52)
	at com.spectralogic.ds3client.commands.AbstractResponse.<init>(AbstractResponse.java:62)
	at com.spectralogic.ds3client.commands.BulkResponse.<init>(BulkResponse.java:34)
	at com.spectralogic.ds3client.commands.BulkPutResponse.<init>(BulkPutResponse.java:24)
	at com.spectralogic.ds3client.Ds3ClientImpl.bulkPut(Ds3ClientImpl.java:115)
	at com.spectralogic.ds3client.helpers.Ds3ClientHelpersImpl.innerStartWriteJob(Ds3ClientHelpersImpl.java:69)
	at com.spectralogic.ds3client.helpers.Ds3ClientHelpersImpl.startWriteJob(Ds3ClientHelpersImpl.java:51)
	at ch.cyberduck.core.spectra.SpectraBulkService.pre(SpectraBulkService.java:75)
	... 36 more

```

**Comment by dkocher** [comment]
```
DEBUG wire - http-outgoing-2 >> "PUT /_rest_/bucket/test.cyberduck.ch?max_upload_size=100000000000&operation=start_bulk_put HTTP/1.1[\r][\n]"
DEBUG wire - http-outgoing-2 >> "HOST: bplab.spectralogic.com:80[\r][\n]"
DEBUG wire - http-outgoing-2 >> "DATE: Wed, 20 Jan 2016 14:08:09 +0000[\r][\n]"
DEBUG wire - http-outgoing-2 >> "Content-Type: application/xml; charset=ISO-8859-1[\r][\n]"
DEBUG wire - http-outgoing-2 >> "Naming-Convention: s3[\r][\n]"
DEBUG wire - http-outgoing-2 >> "Authorization: AWS c3BlY3RyYQ==:FHlW0KlVmd2B/k4m6Mb5y95YFiQ=[\r][\n]"
DEBUG wire - http-outgoing-2 >> "Content-Length: 85[\r][\n]"
DEBUG wire - http-outgoing-2 >> "Connection: Keep-Alive[\r][\n]"
DEBUG wire - http-outgoing-2 >> "User-Agent: Cyberduck/null.null (Mac OS X/10.11.2) (x86_64)[\r][\n]"
DEBUG wire - http-outgoing-2 >> "[\r][\n]"
DEBUG wire - http-outgoing-2 >> "<Objects><Object Name="42a6e19d-20f7-48a6-99f1-5c83126fdddf.txt" Size="0"/></Objects>"
DEBUG wire - http-outgoing-2 << "HTTP/1.1 200 OK[\r][\n]"
DEBUG wire - http-outgoing-2 << "Server: Apache-Coyote/1.1[\r][\n]"
DEBUG wire - http-outgoing-2 << "RequestHandler-Version: 12.1333186E7BD085A9B75B5F4BB1F3C88C[\r][\n]"
DEBUG wire - http-outgoing-2 << "x-amz-request-id: 308081[\r][\n]"
DEBUG wire - http-outgoing-2 << "Content-Type: text/xml;charset=UTF-8[\r][\n]"
DEBUG wire - http-outgoing-2 << "Content-Language: en-US[\r][\n]"
DEBUG wire - http-outgoing-2 << "Content-Length: 711[\r][\n]"
DEBUG wire - http-outgoing-2 << "Date: Wed, 20 Jan 2016 14:14:20 GMT[\r][\n]"
DEBUG wire - http-outgoing-2 << "[\r][\n]"
DEBUG wire - http-outgoing-2 << "<MasterObjectList BucketName="test.cyberduck.ch" CachedSizeInBytes="0" ChunkClientProcessingOrderGuarantee="IN_ORDER" CompletedSizeInBytes="0" JobId="f1b8ae91-191e-4aed-bb7e-05e41b74de96" OriginalSizeInBytes="0" Priority="HIGH" RequestType="PUT" StartDate="2016-01-20T14:14:20.000Z" Status="IN_PROGRESS" UserId="36692c31-f2db-4aa3-9edd-f063c1546b2e" UserName="spectra"><Nodes><Node EndPoint="192.30.190.151" HttpPort="80" HttpsPort="443" Id="e152c474-bba3-11e4-8c76-0007432934b0"/></Nodes><Objects ChunkId="1ea9f575-4074-4c7a-bf2c-edefefb00890" ChunkNumber="0"><Object InCache="false" Latest="true" Length="0" Name="42a6e19d-20f7-48a6-99f1-5c83126fdddf.txt" Offset="0" Version="1"/></Objects></MasterObjectList>"
```

**Comment by dkocher** [comment]
Do we need to set `productionBuild` in _ds3_sdk.properties_`

**Comment by rpmoore** [comment]
Are you using the latest java sdk? (v1.2.4)

**Comment by dkocher** [comment]
```
[INFO] ch.cyberduck:spectra:jar:4.8.0-SNAPSHOT
[INFO] +- ch.cyberduck:core:jar:4.8.0-SNAPSHOT:compile
[INFO] |  +- ch.cyberduck:config:jar:4.8.0-SNAPSHOT:compile
[INFO] |  +- net.java.dev.jets3t:jets3t:jar:0.9.4.1:compile
[INFO] |  |  +- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] |  |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[INFO] |  |  +- javax.activation:activation:jar:1.1.1:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.4:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.1:compile
[INFO] |  +- org.apache.httpcomponents:httpmime:jar:4.5.1:compile
[INFO] |  +- commons-net:commons-net:jar:3.4:compile
[INFO] |  +- org.apache.commons:commons-pool2:jar:2.4.2:compile
[INFO] |  +- commons-io:commons-io:jar:2.4:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] |  +- org.bouncycastle:bcprov-jdk15on:jar:1.53:compile
[INFO] |  +- org.bouncycastle:bcpkix-jdk15on:jar:1.53:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.12:compile
[INFO] |  +- org.slf4j:slf4j-log4j12:jar:1.7.12:compile
[INFO] |  +- org.slf4j:jul-to-slf4j:jar:1.7.12:compile
[INFO] |  +- com.googlecode.plist:dd-plist:jar:1.16:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.2.4:compile
[INFO] |  \- net.java.dev.jna:jna:jar:4.2.1:compile
[INFO] +- ch.cyberduck:s3:jar:4.8.0-SNAPSHOT:compile
[INFO] |  +- ch.cyberduck:webdav:jar:4.8.0-SNAPSHOT:compile
[INFO] |  |  \- com.github.lookfirst:sardine:jar:5.6:compile
[INFO] |  +- ch.cyberduck:udt:jar:4.8.0-SNAPSHOT:compile
[INFO] |  |  \- com.barchart.udt:barchart-udt-bundle:jar:2.3.0:compile
[INFO] |  +- com.jamesmurty.utils:java-xmlbuilder:jar:1.1:compile
[INFO] |  |  \- net.iharder:base64:jar:2.3.8:compile
[INFO] |  \- com.amazonaws:aws-java-sdk-iam:jar:1.10.34:compile
[INFO] |     \- com.amazonaws:aws-java-sdk-core:jar:1.10.34:compile
[INFO] |        \- joda-time:joda-time:jar:2.8.1:compile
[INFO] +- ch.cyberduck:test:pom:4.8.0-SNAPSHOT:test
[INFO] |  +- ch.cyberduck:core:test-jar:tests:4.8.0-SNAPSHOT:test
[INFO] |  \- junit:junit:jar:4.12:test
[INFO] |     \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- com.spectralogic.ds3:ds3-sdk:jar:1.2.3:compile
[INFO] |  +- org.slf4j:jcl-over-slf4j:jar:1.7.13:compile
[INFO] |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.6.4:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.6.4:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.4:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.6.4:compile
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.6.4:compile
[INFO] |  |  \- org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
[INFO] |  +- com.google.guava:guava:jar:19.0:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  +- org.codehaus.woodstox:woodstox-core-asl:jar:4.4.1:compile
[INFO] |  |  \- javax.xml.stream:stax-api:jar:1.0-2:compile
[INFO] |  \- com.google.code.findbugs:annotations:jar:3.0.0:compile
[INFO] \- log4j:log4j:jar:1.2.17:compile
```

**Comment by rpmoore** [comment]
Did you build the jar yourself or did you download our pre-assembled jar?  The version you are using should have what you need to get around this.

**Comment by dkocher** [comment]
The sha1 checksum for `com.spectralogic.ds3:ds3-sdk:jar:1.2.4`is `1c09cf23c6bd5394ae7169c26952fecccc19fa43`.

**Comment by dkocher** [comment]
Setting the environement variable productionBuild=true fixes this issue.

**Comment by rpmoore** [comment]
Right, but the jar you had from the dependency output from gradle was v1.2.3.  The version on bintray should have the correct property file in it.  If that is not working, are you loading the jar files with your own classloader?

**Comment by dkocher** [comment]
Looks like my IDE was caching the `1.2.3` version for the tests run which had `productionBuild` set to `false` in _ds3_sdk.properties_.
