### ISSUE TITLE
Failed to generate HMAC

### ISSUE THREAD

**Issue by dkocher** [SpectraLogic/ds3_java_sdk#429]
i see the below error against a test installation.

````
	Caused by: java.security.SignatureException: Failed to generate HMAC : null
		at com.spectralogic.ds3client.utils.Signature.calculateRFC2104HMAC(Signature.java:59)
		at com.spectralogic.ds3client.utils.Signature.signature(Signature.java:70)
		at com.spectralogic.ds3client.NetworkClientImpl$RequestExecutor.getSignature(NetworkClientImpl.java:315)
		at com.spectralogic.ds3client.NetworkClientImpl$RequestExecutor.addHeaders(NetworkClientImpl.java:257)
		at com.spectralogic.ds3client.NetworkClientImpl$RequestExecutor.execute(NetworkClientImpl.java:211)
		at com.spectralogic.ds3client.NetworkClientImpl.getResponse(NetworkClientImpl.java:162)
		at com.spectralogic.ds3client.Ds3ClientImpl.bulkGet(Ds3ClientImpl.java:110)
		at com.spectralogic.ds3client.helpers.Ds3ClientHelpersImpl.innerStartReadJob(Ds3ClientHelpersImpl.java:106)
		at com.spectralogic.ds3client.helpers.Ds3ClientHelpersImpl.startReadJob(Ds3ClientHelpersImpl.java:100)
		at ch.cyberduck.core.spectra.SpectraBulkService.pre(SpectraBulkService.java:136)
		... 17 more
````

**Comment by rpmoore** [comment]
What JVM are you using?

**Comment by dkocher** [comment]
That is 8u112.

**Comment by rpmoore** [comment]
In looking at the signature code, it's not immediately obvious what the error might be.  I'm going to improve this code in our next release, which will be early next week.

In the meantime, it will be helpful if you can provide me with some extra details.  With the debug logging level enabled, I need the string to sign, and then if the secret key or access key were null.

**Comment by rpmoore** [comment]
We just released 3.2.9 which has this additional logging that will help with debugging this issue when it's encountered again.  3.2.9 introduces a couple API changes that makes writing unit tests easier.  I'll be writing a guide talking about what the update means for current api users over the next couple days.

**Comment by dkocher** [comment]
Should have mentioned we are still on 1.2.6.

**Comment by rpmoore** [comment]
Without the enhancements that were just made I won't be able to determine what the issue is.

**Comment by dkocher** [comment]
I suppose either one of the input parameters is `null`.

**Comment by dkocher** [comment]
We have identified the issue to be on our end with nullified credentials after login.

**Comment by rpmoore** [comment]
I'm glad that you were able to identify the issue.  I'm curious, was the sdk throwing an IllegalArgumentException when you passed in nullified credentials?
