### ISSUE TITLE
NPE in 5.0.1 Java SDK

### ISSUE THREAD

**Issue by LogicalChaos** [SpectraLogic/ds3_java_sdk#551]
The check for VersionID should be nullableEquals.  Ask me how I know.
```
Exception in thread "main" java.lang.NullPointerException
        at com.spectralogic.ds3client.models.bulk.Ds3Object.equals(Ds3Object.java:129)
        at java.util.ArrayList.remove(ArrayList.java:528)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.spectralogic.WrittenObjects.addAll(WrittenObjects.java:64)
        at com.spectralogic.DS3Fill.fillOneSet(DS3Fill.java:109)
        at com.spectralogic.Main.lambda$main$1(Main.java:88)
        at com.spectralogic.util.Timer.timeBlock(Timer.java:55)
        at com.spectralogic.Main.main(Main.java:88)
```

**Comment by rpmoore** [comment]
This is fixed, and will be in the 5.0.2 version of the SDK.
